[package]
name = "hyper-async-router"
version = "0.1.0"
authors = ["Håvar Nøvik"]

[dependencies]
route-recognizer = "0.1.12"
futures = "0.1.15"
http = "0.1"

[dependencies.hyper]
version = "0.11.7"
features = ["compat"]

[dev-dependencies]
tokio-service = "0.1.0"
