[package]
name = "hyper-async-router"
version = "0.1.0"
authors = ["Håvar Nøvik"]

[dependencies]
hyper = "0.11.7"
route-recognizer = "0.1.12"
futures = "0.1.15"

[dev-dependencies]
tokio-service = "0.1.0"
